language: ruby
cache: bundler
sudo: false
script:
  - bundle exec rake bamboo:prepare
  - bundle exec rake db:migrate
  - bundle exec rake knapsack:rspec
env:
  global:
    - CI_NODE_TOTAL=4
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=4