language: node_js
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run copy-secrets
  - npm run silent-test
branches:
  only: # Only build master. All pull requests also get built
    - master
deploy:
  provider: script
  script: bin/ecc-sync
  on:
    branch: master
    repo: nasa/earthdata-search
