language: ruby
cache: bundler
sudo: false
script:
  - bundle exec rake travis:ci
env:
  global:
    - CI_NODE_TOTAL=4
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - JASMINE=true
deploy:
  provider: script
  script: scripts/sync
  on:
    branch: master
    repo: nasa/earthdata-search