portals: &portals
  carve:
    title: CARVE
    params:
      project:
        - CARVE
    logos:
      - image: https://daac.ornl.gov/graphics/daac_logo.jpg
        link: https://daac.ornl.gov
    nav:
      - title: CARVE Home
        link: https://carve.ornl.gov/

  airmoss:
    title: AirMOSS
    params:
      project:
        - AirMOSS
    logos:
      - image: https://daac.ornl.gov/graphics/daac_logo.jpg
        link: https://daac.ornl.gov
    nav:
      - title: AirMOSS Home
        link: https://airmoss.ornl.gov

examples: &examples
  example:

  simple:
    params:
      echo_collection_id:
        - C90762182-LAADS

  complex:
    title: Complex
    params:
      echo_collection_id:
        - C90762182-LAADS
    logos:
      - image: http://placehold.it/75x50
        link: https://example.com/logo
    nav:
      - title: Example Link
        link: https://example.com/1
      - title: Another Example
        link: https://example.com/1
    scripts:
      - edsc-portal.example.min.js

defaults:
  <<: *examples
  <<: *portals

production:
  <<: *portals
