defaults: &defaults
  example:
  cwic:
    params:
      tag_key:
        - org.ceos.wgiss.cwic.granules.prod
      features:
        - Int'l / Interagency
  ornl_example:
    params:
      provider:
        - ORNL_DAAC
    #scripts:
    #  - edsc.portal.cwic.js


test: &test
  <<: *defaults

  simple:
    params:
      echo_collection_id:
        - C1219032686-LANCEMODIS

development:
  <<: *test