token_defaults: &token_defaults
  token_type: 'Bearer'
  endpoint: '/api/users/edsc'
  username: 'edsc'
  expires_in: 3600
  expires: 9999999999

urs_tokens:
  edsc:
    <<: *token_defaults
    access_token: <%= (ENV['test_urs_edsc_access_token'] || 'edsc-access').inspect %>
    refresh_token: <%= (ENV['test_urs_edsc_refresh_token'] || 'edsc-refresh').inspect %>
  expired_token:
    <<: *token_defaults
    access_token: <%= (ENV['test_urs_expired_access_token'] || 'expired-access').inspect %>
    refresh_token: <%= (ENV['test_urs_expired_refresh_token'] || 'expired-refresh').inspect %>
    expires: 1
  edscbasic:
    <<: *token_defaults
    access_token: <%= (ENV['test_urs_edscbasic_access_token'] || 'edscbasic-access').inspect %>
    refresh_token: <%= (ENV['test_urs_edscbasic_refresh_token'] || 'edscbasic-refresh').inspect %>
    endpoint: "/api/users/edscbasic"
    username: "edscbasic"
